// Generated by CoffeeScript 1.6.3

var portfolio = angular.module('content', []);

portfolio.config(function($routeProvider) {
  return $routeProvider
    .when('/about',
      {
        templateUrl: 'partials/about.html'
      })
    .when('/contact',
      {
        templateUrl: 'partials/contact.html'
      })
    .when('/projects',
      {
        templateUrl: 'partials/projects.html'
      })
    .when('/resume',
      {
        templateUrl: 'partials/resume.html'
      })
    .otherwise({ redirectTo: '/about'
  });
});// Generated by CoffeeScript 1.6.3

