// Generated by CoffeeScript 1.6.3
require('newrelic');

var fs = require('fs');
var parse = require('url').parse;

require('http').createServer(function(req, res) {
  var path = parse(req.url).path;
  if (path === '/') path = '/index.html';  
  fs.readFile('.' + path, function(err, data) {
    if (err) {
      console.error(err);
      if (err.code === 'ENOENT') {
        res.writeHead(404);
        res.end('Not Found: ' + path);
      }
      else {
        res.writeHead(500);
        res.end('Internal Server Error: ' + err);
      }
    }
    else {
      console.log('Served ' + path);
      res.end(data);
    }
  });
}).listen(process.env.PORT || 5000);
console.log('Listening on ' + (process.env.PORT || 5000));

